name: Validate with Hacs

on:
  workflow_dispatch:

jobs:
  validate_hacs:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v5"
      - name: HACS validation
        uses: "hacs/action@main"
        with:
          category: "integration"
